# Generated by Django 3.0.8 on 2020-07-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
