# Generated by Django 3.0.8 on 2020-07-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0002_auto_20200714_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='pub_date',
        ),
    ]
